name: Release

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx conventional-github-releaser -p angular
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
